<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Log extends Model
{
    use HasFactory;

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['user_generate'];

    /**
     * Get the user that owns the user.
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function getUserGenerateAttribute()
    {
        if ($this->attributes['user_id']) {
            return $this->user->name;
        }
        return 'Generated by migration';
    }
}
